config/routes.rb
Rails.application.routes.draw do
  devise_for :people, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: "people#index"

  resources :marbles
  resources :people

end

app/models/marble.rb
class Marble < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
	has_many :marbles

	def self.find_for_facebook_oauth(auth, signed_in_resource=nil)

		person = Person.where(:provider => auth.provider, :uid => auth.uid).first

		if person
			return person
		else
			registered_person = Person.where(:email => auth.info.email).first
			if registered person
				return registered_person
			else
				person = Person.create!(username:auth.extra.raw_info.name, provider:auth.provider, uid:auth.uid, email:auth.info.email,
					password:Devise.friendly_token[0,20],)
			end
		end
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/marbles_controller.rb
class MarblesController < ApplicationController
  before_action :set_marble, only: [:show, :edit, :update, :destroy]

  # GET /marbles
  # GET /marbles.json
  def index
    @marbles = Marble.all
  end

  # GET /marbles/1
  # GET /marbles/1.json
  def show
  end

  # GET /marbles/new
  def new
    @marble = Marble.new
  end

  # GET /marbles/1/edit
  def edit
  end

  # POST /marbles
  # POST /marbles.json
  def create
    @marble = Marble.new(marble_params)

    respond_to do |format|
      if @marble.save
        format.html { redirect_to @marble, notice: 'Marble was successfully created.' }
        format.json { render :show, status: :created, location: @marble }
      else
        format.html { render :new }
        format.json { render json: @marble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marbles/1
  # PATCH/PUT /marbles/1.json
  def update
    respond_to do |format|
      if @marble.update(marble_params)
        format.html { redirect_to @marble, notice: 'Marble was successfully updated.' }
        format.json { render :show, status: :ok, location: @marble }
      else
        format.html { render :edit }
        format.json { render json: @marble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marbles/1
  # DELETE /marbles/1.json
  def destroy
    @marble.destroy
    respond_to do |format|
      format.html { redirect_to marbles_url, notice: 'Marble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marble
      @marble = Marble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marble_params
      params.require(:marble).permit(:name, :color, :person_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		auth = env["omniauth.auth"]

		@person = Person.find_for_twitter_oauth(request.env["omniauth.auth"],current_person)
		if @person.persisted?
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
			sign_in_and_redirect @person, :event => :authentication
		else
			session["deivse.facebook_uid"] = request.env["omniauth.auth"]
			redirect_to new_person_registration_url
		end
	end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:username, :provider, :uid, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marbles_helper.rb
module MarblesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if person_signed_in? %>
	Signed in as <%= current_person.username %>. Not you?
	<%= link_to "Sign out", destroy_person_session_path, :method => :delete %>
<% else %>
	<%= link_to "Sign in with Facebook",person_omniauth_authorize_path(:facebook) %>
<!-- 	link_to "Sign in with Google", person_omniauth_authorize_path(:google) 
 -->
<% end %>

<%= yield %>

<%= ENV['FACEBOOK_APPID'] %>

</body>
</html>

app/views/marbles/_form.html.erb
<%= form_for(@marble) do |f| %>
  <% if @marble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marble.errors.count, "error") %> prohibited this marble from being saved:</h2>

      <ul>
      <% @marble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marbles/edit.html.erb
<h1>Editing Marble</h1>

<%= render 'form' %>

<%= link_to 'Show', @marble %> |
<%= link_to 'Back', marbles_path %>

app/views/marbles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Marbles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marbles.each do |marble| %>
      <tr>
        <td><%= marble.name %></td>
        <td><%= marble.color %></td>
        <td><%= marble.person %></td>
        <td><%= link_to 'Show', marble %></td>
        <td><%= link_to 'Edit', edit_marble_path(marble) %></td>
        <td><%= link_to 'Destroy', marble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marble', new_marble_path %>

app/views/marbles/new.html.erb
<h1>New Marble</h1>

<%= render 'form' %>

<%= link_to 'Back', marbles_path %>

app/views/marbles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @marble.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @marble.color %>
</p>

<p>
  <strong>Person:</strong>
  <%= @marble.person %>
</p>

<%= link_to 'Edit', edit_marble_path(@marble) %> |
<%= link_to 'Back', marbles_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.username %></td>
        <td><%= person.provider %></td>
        <td><%= person.uid %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @person.username %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @person.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @person.uid %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>